---
name: "Terraform"

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_comment: true

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow
      - name: Update module usage docs and push any changes back to PR branch
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          args: "--sort --sort-by required"
          git-commit-message: "terraform-docs: Update module usage"
          git-push: "true"
          output-file: README.md
          output-method: inject
          working-dir: .
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
